### ISSUE TITLE
Make it possible to provide extra attributes to Measurements payload  

### ISSUE THREAD

**Issue by codecapitano** [grafana/faro-web-sdk#254]
## Description

The measurement API is missing the option to add attributes/context data like the `error`, log` or `event` APIs are doing.
User often need a possibility to transport extra information within the respective Meta. 

## Proposed solution

Add an option to `pushMeasurement` API to extra data.

## Context
[Community Slack](https://grafana.slack.com/archives/C048UH68BM5/p1692729020402719)
```[tasklist]
### Tasks
- [x] Add functionallity to Web-SDK
- [x] Add functionallity to the Reciever
- [ ] Add functionallity to the Agent
- [x] Update Faro docs
```

**Comment by codecapitano** [comment]
- [Web-SDK PR](https://github.com/grafana/faro-web-sdk/pull/256)
- [Faro Receiver PR](https://github.com/grafana/app-o11y-kwl-endpoint/pull/262)
- [Grafana Website PR (docs) ](https://github.com/grafana/website/pull/15059)
- Grafana Agent: TODO
